If this file can be seen from the functions.py file than the user tried to import the library from within the git repository.
Please change the directory!